---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-k8s-demo-service
spec:
  type: LoadBalancer
  selector:
    app: spring-cloud-k8s-demo-app
  ports:
    - name: spring-cloud-k8s-demo-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-k8s-demo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-k8s-demo-app
        version: "1.0"
    spec:
      containers:
        - name: spring-cloud-k8s-demo
          image: docker.io/bricerisingslalom/spring-cloud-k8s-demo:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
              cpu: .5
          ports:
            - containerPort: 8080
